suzerain: fix get_logger for descendent
Need to return a non-reference, which is okay since logger_type
is a smart pointer under the covers.
../../../sz/suzerain/support/logging.hpp:372:42: error: invalid initialization of non-const reference of type ‘suzerain::support::logging::logger_type& {aka log4cxx::helpers::ObjectPtrT<log4cxx::Logger>&}’ from an rvalue of type ‘log4cxx::LoggerPtr {aka log4cxx::helpers::ObjectPtrT<log4cxx::Logger>}’

git-svn-id: https://svn.ices.utexas.edu/repos/pecos/suzerain/trunk@38059 0bd85f0b-c151-43b9-a1e9-27231104551f