suzerain: relax failing precision for buildbot
Failures were like test_pencilfft_1D.cpp(257): fatal error in "test_1d_out_of_place_7": difference{1.76664e-12%} between out_real*NC{0.19952943293322087} and buffer[i][0]{0.19952943293321734} exceeds 1.0880185641326534e-12%
which is down in the noise bits.


git-svn-id: https://svn.ices.utexas.edu/repos/pecos/suzerain/trunk@7090 0bd85f0b-c151-43b9-a1e9-27231104551f