suzerain: #2980 capture challenging data
Breaks with
../../sz/tests/test_bl.cpp(264): fatal error in "find_edge": critical check SUZERAIN_SUCCESS == suzerain_bl_find_edge( coeffs_H0, &location, dB.get(), b.bw, b.dbw) failed [0 != -2]
which is interesting as -2 is the code for SUZERAIN_CONTINUE indicating
that the call the suzerain_bspline_crossing likely couldn't reach
the requested GSL_DBL_EPSILON tolerance in the provide number of
iterations.

Investigating...

git-svn-id: https://svn.ices.utexas.edu/repos/pecos/suzerain/trunk@42275 0bd85f0b-c151-43b9-a1e9-27231104551f